services:
  web:
    image: ${DOCKERHUB_USERNAME}/devops-docker-app:${TAG:-latest}
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8080}:8080"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3
